//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int CarID { get; set; }
        public string mark { get; set; }
        public string producer { get; set; }
        public string color { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> year { get; set; }
        public string photo { get; set; }
    
        public virtual Mark Mark1 { get; set; }
    }
}
